[toolchain]
anchor_version = "0.31.1" # Or your specific version

[features]
seeds = false
skip-lint = false

[programs.localnet] # Or [programs.devnet], or just [programs.mainnet] if you rename
hello_solana = "FQLt6TZ1r15Pvj8ibh8u7RMcFz2MGeKfNnHm5QsWisdg" # <-- This will be updated after deploy

[registry]
url = "https://api.apr.dev"

[provider]
# Change this line:
cluster = "devnet"
# Ensure this points to a keypair file funded with DEVNET SOL:
wallet = "~/.config/solana/id.json" # Or your specific deployer keypair path

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"